name: Deploy ke VPS

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t portofolio-react .

      - name: Save image ke tar
        run: docker save portofolio-react > portofolio.tar

      - name: Upload ke VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          source: "portofolio.tar"
          target: "/var/www/"


      - name: Deploy di VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          script: |
            cd /var/www

            echo "Stop dan hapus container lama..."
            docker stop portofolio || true
            docker rm portofolio || true

            echo "Load image baru..."
            docker load < portofolio.tar

            echo "Run container baru..."
            docker run -d -p 3000:80 --name portofolio portofolio-react

            echo "Deploy selesai"
