name: Deploy ke VPS

on:
  push:
    branches:
    - main

job:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy ke VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          script: |
            cd /var/www/portofolio-website-react
            git pull origin main
            npm install
            npm run build
            systemctl restart nginx
